version: '3.2'

services:
  db:
    container_name: lb2_dev_db
    image: postgres
    volumes: [ "../db-docker-data:/var/lib/postgresql/data" ]
    environment:
      POSTGRES_PASSWORD: verysecure123

  app:
    container_name: lb2_dev_app
    build: .
    image: elixir-dev
    tty: true
    stdin_open: true
    depends_on: [ db ]
    volumes: [ "../..:/app" ]
    ports: [ "4000:4000" ]
    environment:
      PG_HOST: db
